name: catenary
description: Real-time transit tracking and routing.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  maplibre_gl:
      git:
        url: https://github.com/maplibre/flutter-maplibre-gl.git
        ref: main
  cupertino_icons: ^1.0.2
  flutter_rust_bridge: ^1.31.0
  freezed_annotation: ^2.0.3
  location: ^5.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  location: ^5.0.0